spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dbAppTravel?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
        username: root
        password: 123456
    
    jpa:
        show-sql: true

jwt:
    #Tùy vào thuật toán mã hóa mà độ dài tối thiểu của key có thể khác nhau
    secret: ChuoiBiMatSieuCapVipProVaPhaiRatLaDaiDeDamBaoAnToanChoThuatToanHS512
    #Thời gian sống của token
    expiration: 86400000